name: Zbierz Statystyki ShowUp

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Zmieniamy nazwę kroku na bardziej adekwatną do misji diagnostycznej
      - name: Run diagnostics to save page source
        run: python scraper.py

      # Ten krok zapisze wygenerowany plik jako "artefakt" do pobrania
      - name: Upload page source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-source # Nazwa artefaktu
          path: page_content.html # Plik, który ma zostać spakowany
