name: Zbierz i Wizualizuj Statystyki

on:
  workflow_dispatch:

jobs:
  build-and-visualize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # --- ZMIANA: Używamy nowszej wersji Pythona ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- NOWY KROK: Cache'owanie zależności dla przyspieszenia ---
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Krok 1 - Zbierz nowe dane
        run: python scraper.py

      - name: Krok 2 - Wygeneruj nowy wykres
        run: python generate_chart.py

      - name: Krok 3 - Zapisz wyniki (dane i wykres)
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dane.csv index.html
          git diff --staged --quiet || git commit -m "Aktualizacja danych i wykresu"
          git push
