name: Zbierz i Wizualizuj Statystyki

on:
  schedule:
    # Uruchom co 20 minut. UWAGA: Może przekroczyć darmowy limit!
    # Bezpieczniejsza opcja to '*/30 * * * *' (co 30 minut)
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build-and-visualize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Krok 1 - Zbierz nowe dane
        run: python scraper.py

      - name: Krok 2 - Wygeneruj nowy wykres
        run: python generate_chart.py

      - name: Krok 3 - Zapisz wyniki (dane i wykres)
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dane.csv index.html
          # Sprawdź, czy są zmiany, i tylko wtedy je zapisz
          git diff --staged --quiet || git commit -m "Aktualizacja danych i wykresu"
          git push
