name: Zbierz Statystyki ShowUp

on:
 schedule:
    # Uruchom co 20 minut (o :00, :20, :40 każdej godziny)
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- NOWY KROK: INSTALACJA GOOGLE CHROME ---
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        run: python scraper.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dane.csv
          git diff --staged --quiet || git commit -m "Aktualizacja danych"
          git push
